### ISSUE TITLE
'Cannot open source file fftw3.h'

### ISSUE THREAD

**Issue by open-gear** [dealias/fftwpp#10]
When compiling my code with fftw++, a bunch of errors popped up. After fixing my own, it looked like most of them were the result of a missing file in fftw++.h . I checked the folders I'd downloaded (and I downloaded fftw++ at most four days ago) and there is no fftw3.h in the folders. I also tried dropping one in from FFTW (one of the other problem areas was line extern "C" fftw_plan Planner(fftw *F, Complex *in, Complex *out);), but that didn't work either... which seems to indicate that the file was excluded on purpose but a number of parts weren't removed from the code. Okay.

If someone could reply soon, that would be great; I'm doing some time-sensitive stuff. If not... well, at least this stuff will be fixed for the next person.

**Comment by johncbowman** [comment]
The file fftw3.h is part of FFTW. You have to install that first. Note that some distributions split FFTW into two parts (like fftw and fftw-devel). You need version 3 (the current release is 3.3.7).

**Comment by open-gear** [comment]
Hey, thanks for replying.


Sorry about posting that; my idiot brain didn't correctly register the 'header file' part of the program and missed the line on the main site about FFTW being needed. I only realized this a little earlier today.


Thanks again.

________________________________
