### ISSUE TITLE
I met the following error when i compile example in mpi directory

### ISSUE THREAD

**Issue by ztdepztdep** [dealias/fftwpp#12]
/usr/include/bits/getopt_core.h:91:12: error: declaration of ‘int getopt(int, char* const*, const char*) throw ()’ has a different exception specifier
 extern int getopt (int ___argc, char *const *___argv, const char *__shortopts)

**Comment by johncbowman** [comment]
Fixed in commit  6d559c2393e2f817e615cfddf58b52ac70e65b77.
