### ISSUE TITLE
Configuration fails since 'No fftw_malloc in -lfftw3'

### ISSUE THREAD

**Issue by yonatansmn** [dealias/fftwpp#16]
I try to configure C code as follows:
./configure --with-fftw=/usr/local/fftw-3.3.6-pl2/
But I receive the error stated in the title. 
I've tried adding the lib directory to the LD_LIBRARY_PATH and configure it with -L.

Thanks for the help

**Comment by johncbowman** [comment]
This indicates an installation problem with your FFTW3 library. Perhaps you inadvertently disabled this at configuration time. I note there is a --with-our-malloc configure option. The latest version of FFTW3
is 3.3.8, so this would be a good time to upgrade. Here are the configuration options that I use:

configure --enable-sse2 --enable-shared --prefix=/usr --enable-mpi --enable-openmp --disable-fortran --enable-avx2

You are strongly recommended to use fftw_malloc:
http://www.fftw.org/fftw3_doc/Memory-Allocation.html
