### ISSUE TITLE
Unresolved external symbols in VS2019 build

### ISSUE THREAD

**Issue by SRudinsky** [dealias/fftwpp#17]
I have a Visual Studio project using FFTWpp and I have run into the following build problem. I am getting errors of unresolved external symbols. I am using fftwpp from vcpkg but I obtained the same errors using the library directly. The errors arise in the obj file. The output is the following.

>error LNK2019: unresolved external symbol "public: __cdecl fftwpp::ThreadBase::ThreadBase(void)" (??0ThreadBase@fftwpp@@QEAA@XZ) referenced in function "public: __cdecl fftwpp::fftw::fftw(unsigned int,int,unsigned int,unsigned int)" (??0fftw@fftwpp@@QEAA@IHII@Z)
error LNK2001: unresolved external symbol "char const * const fftwpp::inout" (?inout@fftwpp@@3PEBDEB)
error LNK2001: unresolved external symbol "public: static unsigned int fftwpp::fftw::effort" (?effort@fftw@fftwpp@@2IA)
error LNK2001: unresolved external symbol "public: static unsigned int fftwpp::fftw::maxthreads" (?maxthreads@fftw@fftwpp@@2IA)
error LNK2001: unresolved external symbol "public: static double fftwpp::fftw::testseconds" (?testseconds@fftw@fftwpp@@2NA)
error LNK2001: unresolved external symbol "public: static struct fftw_plan_s * (__cdecl* fftwpp::fftw::planner)(class fftwpp::fftw *,class std::complex<double> *,class std::complex<double> *)" (?planner@fftw@fftwpp@@2P6APEAUfftw_plan_s@@PEAV12@PEAV?$complex@N@std@@1@ZEA)

Do you have any ideas on how to fix this?

**Comment by johncbowman** [comment]
That means you forgot to compile and link in fftw++.cc.

**Comment by SRudinsky** [comment]
How can I do this in windows to link with a visual studio project?

Samantha Rudinsky, PhD
Steam Instruments

**Comment by milahu** [comment]
thanks to @johncbowman .... you saved my day

can we please add this to the README?
like .... 

> INSTALL AND COMPILE
> to use fftw++.h you must
> 1. add `#include "fftw++.h"` in your program.cpp
> 2. add the header files `fftw++.h`, `seconds.h`, `statistics.h`, `align.h` to your project
> 3. add the source file `fftw++.cc` to your project
> 4. configure your toolchain to compile (and link) `fftw++.cc` (for example in CMakeLists.txt)
> 5. configure your toolchain to link the shared library `fftw3` (`-lfftw3` for g++) (or add project dependency `list(APPEND PKGDEPS fftw3>=3.3.8)` for cmake)

in my case, `ld` produced the first error
```
/usr/bin/ld: CMakeFiles/pulseview.dir/pv/views/trace/analogsignal.cpp.o: in function `fftwpp::fftw::Setout(std::complex<double>*, std::complex<double>*)':
/tmp/pulseview/fft/fftw++.h:408: undefined reference to `fftwpp::inout'
```
my project is using cmake build system, so i had to change the file `CMakeLists.txt` to
```
if(ENABLE_SPECTRUM_ANALYZER)
  list(APPEND pulseview_SOURCES
    fft/fftw++.cc
  )
endif()
```

@SRudinsky here is how to [Add a new source file in MS visual studio](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-a-standard-cpp-program-cpp?view=vs-2019#add-a-new-source-file)
took me like two seconds of google search : P
