### ISSUE TITLE
What is the difference of array and Array.

### ISSUE THREAD

**Issue by ztdepztdep** [dealias/fftwpp#22]
I have noticed there are two kinds of array and Array. Could you please give me some suggestions about the differences between these two arries. 
  Can we set the storage format of the array. (c like or fortran like.)

**Comment by johncbowman** [comment]
Array allows for negative indices, the special case array is optimized for non-negative indices. For usage examples, see
https://www.math.ualberta.ca/~bowman/Array.html.

The multi-dimensional instances store data in row-major format to be consistent with standard mathematical matrix notation, where the row index is listed first. As in C and C++, the indexing of the array classes (and the default indexing of the Array classes) are zero based.

**Comment by ztdepztdep** [comment]
does fft0  represent the inplace transform?

**Comment by johncbowman** [comment]
No, fft0 shifts the Fourier origin to the midpoint of the data. This is
useful for 2D & 3D Hermitian ffts (e.g. for pseudospectral codes):
//   rcfft2d Forward(nx,ny,in,out);
//   Forward.fft(in,out);       // Origin of Fourier domain at (0,0)
//   Forward.fft0(in,out);      // Origin of Fourier domain at (nx/2,0);

For an inplace transform, simply call fft with one argument (or
equivalently, with out=in).
