### ISSUE TITLE
isinf, isnan, etc. in Complex.h

### ISSUE THREAD

**Issue by taranu** [dealias/fftwpp#7]
Hi,

The isfinite() function in Complex.h calls isinf and isnan, but these should be std::isinf and std::isnan if including cmath (or include math.h instead), as per this discussion:

http://stackoverflow.com/questions/18128899/is-isnan-in-the-std-namespace-more-in-general-when-is-std-necessary-optio

**Comment by johncbowman** [comment]
Thanks; fixed.
