### ISSUE TITLE
mpi test fails

### ISSUE THREAD

**Issue by malcolmroberts** [dealias/fftwpp#8]
Running the mpi unit tests, I had at least one failure using 68797f978635837e71ccc56ea34c828ddf17ef42.  This is with fftw 3.3.6-pl2

Running the case

mpirun -n 8 ./conv3 -x2 -y2 -z2 -N1 -s1 -a1 -X0 -Y1 -Z1 -A2 -T3 -tq 

fails with code 134, which is a memory corruption.  This is reproducable on our cascade test machine.

**Comment by johncbowman** [comment]
A simpler example is
./conv3 -x2 -y2 -z2 -N1 -s1 -a1 -X0 -Y0 -Z0 -A2 -T3

**Comment by johncbowman** [comment]
Fixed in f31cf133f9f4ddf23878cb0a83e848b1f76df1a7.
